<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="91106" started-at="2021-06-25T23:19:58 BDT" finished-at="2021-06-25T23:21:29 BDT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="91106" started-at="2021-06-25T23:19:58 BDT" finished-at="2021-06-25T23:21:29 BDT">
      <class name="monster_lab.RunTestCases">
        <test-method status="PASS" signature="set_connection()[pri:0, instance:monster_lab.RunTestCases@7c29daf3]" name="set_connection" is-config="true" duration-ms="53667" started-at="2021-06-25T23:19:58 BDT" finished-at="2021-06-25T23:20:52 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- set_connection -->
        <test-method status="PASS" signature="check_contact_button()[pri:1, instance:monster_lab.RunTestCases@7c29daf3]" name="check_contact_button" duration-ms="10115" started-at="2021-06-25T23:20:52 BDT" finished-at="2021-06-25T23:21:02 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_contact_button -->
        <test-method status="PASS" signature="check_contact_form()[pri:2, instance:monster_lab.RunTestCases@7c29daf3]" name="check_contact_form" duration-ms="10049" started-at="2021-06-25T23:21:02 BDT" finished-at="2021-06-25T23:21:12 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_contact_form -->
        <test-method status="PASS" signature="check_career_button()[pri:3, instance:monster_lab.RunTestCases@7c29daf3]" name="check_career_button" duration-ms="4880" started-at="2021-06-25T23:21:12 BDT" finished-at="2021-06-25T23:21:17 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_career_button -->
        <test-method status="FAIL" signature="check_open_position()[pri:4, instance:monster_lab.RunTestCases@7c29daf3]" name="check_open_position" duration-ms="12314" started-at="2021-06-25T23:21:17 BDT" finished-at="2021-06-25T23:21:29 BDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://monstar-lab.com/global/about/careers/] but found [https://www.facebook.com/MonstarLab.Bangladesh/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://monstar-lab.com/global/about/careers/] but found [https://www.facebook.com/MonstarLab.Bangladesh/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at monster_lab.RunTestCases.check_open_position(RunTestCases.java:163)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_open_position -->
        <test-method status="PASS" signature="close_connection()[pri:0, instance:monster_lab.RunTestCases@7c29daf3]" name="close_connection" is-config="true" duration-ms="30" started-at="2021-06-25T23:21:29 BDT" finished-at="2021-06-25T23:21:29 BDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close_connection -->
      </class> <!-- monster_lab.RunTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
